=== HM9901/XML/Bai7_2_SinhVien.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="QLSV">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="SinhVien" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaSV">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z][A-Z][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tenSV" type="xs:string"/>
                            <xs:element name="GioiTinh">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="nam|ná»¯"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NgaySinh" type="xs:date"/>
                            <xs:element name="MaLop">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z][A-Z][A-Z][A-Z][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="svKey">
            <xs:selector xpath="SinhVien"/>
            <xs:field xpath="MaSV"/>
        </xs:key>
    </xs:element>
</xs:schema>

=== HM9901/XML/Bai7_2_SinhVien1.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/xsl" href="Bai7_2_SinhVien.xsl"?>
<QLSV xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/HK2-thirdYear/XML/repos/Bai7_2_SinhVien.xsd">
    <SinhVien>
        <MaSV>SV01</MaSV>
        <tenSV>Phan Tấn Cường</tenSV>
        <GioiTinh>nam</GioiTinh>
        <NgaySinh>2006-05-04</NgaySinh>
        <MaLop>CNTT16</MaLop>
    </SinhVien>
    <SinhVien>
        <MaSV>SV02</MaSV>
        <tenSV>Huỳnh Chí Tâm</tenSV>
        <GioiTinh>nam</GioiTinh>
        <NgaySinh>2006-05-04</NgaySinh>
        <MaLop>KTTC15</MaLop>
    </SinhVien>
    <SinhVien>
        <MaSV>SV03</MaSV>
        <tenSV>Vương Chí Dũng</tenSV>
        <GioiTinh>nam</GioiTinh>
        <NgaySinh>2006-05-04</NgaySinh>
        <MaLop>CNTT16</MaLop>
    </SinhVien>
    <SinhVien>
        <MaSV>SV04</MaSV>
        <tenSV>Phạm Đức Nguyên</tenSV>
        <GioiTinh>nam</GioiTinh>
        <NgaySinh>2006-05-04</NgaySinh>
        <MaLop>KTTC15</MaLop>
    </SinhVien>
    <SinhVien>
        <MaSV>SV05</MaSV>
        <tenSV>Trương Mỹ Yến Nhi</tenSV>
        <GioiTinh>nữ</GioiTinh>
        <NgaySinh>2006-05-04</NgaySinh>
        <MaLop>KTTC16</MaLop>
    </SinhVien>
</QLSV>
