=== HM9901/XML/Bai7_3_monhoc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="QLMH">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MonHoc" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaMH" type="xs:string"/>
                            <xs:element name="tenMH" type="xs:string"/>
                            <xs:element name="soGio">
                                <xs:simpleType >
                                    <xs:restriction base="xs:int">
                                        <xs:minExclusive value="4"></xs:minExclusive>
                                        <xs:maxExclusive value="48"></xs:maxExclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="mhKey">
            <xs:selector xpath="MonHoc"/>
            <xs:field xpath="MaMH"/>
        </xs:key>
    </xs:element>
</xs:schema>

=== HM9901/XML/Bai7_3_monhoc1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Bai7_3_monhoc.xsl"?>
<QLMH xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/HK2-thirdYear/XML/repos/Bai7_3_monhoc.xsd">
    <MonHoc>
        <MaMH>CSDL</MaMH>
        <tenMH>Cơ sở dữ liệu</tenMH>
        <soGio>30</soGio>
    </MonHoc>
    <MonHoc>
        <MaMH>MCB</MaMH>
        <tenMH>Mạng Căn bản</tenMH>
        <soGio>30</soGio>
    </MonHoc>
    <MonHoc>
        <MaMH>THDC</MaMH>
        <tenMH>Tin Học Đại Cương</tenMH>
        <soGio>45</soGio>
    </MonHoc>
    <MonHoc>
        <MaMH>THVP</MaMH>
        <tenMH>Tin Học Văn Phòng</tenMH>
        <soGio>45</soGio>
    </MonHoc>
    <MonHoc>
        <MaMH>XLA</MaMH>
        <tenMH>Xử lý ảnh</tenMH>
        <soGio>45</soGio>
    </MonHoc>
</QLMH>
