=== HM9901/XML/KetQua7_4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="QLD">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Diem" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Masv">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-z][a-z][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MaMH">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z][A-Z][A-Z][A-Z]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="DiemThi">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:maxInclusive value="10"/>
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== HM9901/XML/KetQua7_41.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="KetQua7_4.xsl"?>
<QLD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/HK2-thirdYear/XML/repos/KetQua7_4.xsd">
    <Diem>
        <Masv>sv01</Masv>
        <MaMH>THDC</MaMH>
        <DiemThi>10</DiemThi>
    </Diem>
    <Diem>
        <Masv>sv01</Masv>
        <MaMH>THCP</MaMH>
        <DiemThi>9</DiemThi>
    </Diem>
    <Diem>
        <Masv>sv02</Masv>
        <MaMH>THDC</MaMH>
        <DiemThi>8</DiemThi>
    </Diem>
    <Diem>
        <Masv>sv02</Masv>
        <MaMH>THCP</MaMH>
        <DiemThi>6</DiemThi>
    </Diem>
    <Diem>
        <Masv>sv03</Masv>
        <MaMH>THDC</MaMH>
        <DiemThi>7</DiemThi>
    </Diem>
    <Diem>
        <Masv>sv03</Masv>
        <MaMH>THCP</MaMH>
        <DiemThi>9</DiemThi>
    </Diem>
</QLD>
