=== HM9901/XML/QLDH.dtd
<!ENTITY % infoDH "(MSKH, TENKH, DC)">
<!ENTITY % infoMH "(MMH, TENMH, SL, DONGIA)">
<!ELEMENT DOCUMENT (KHACHHANG)+>
<!ELEMENT KHACHHANG (%infoDH;,ORDERS+)>
<!ELEMENT MSKH (#PCDATA)>
<!ELEMENT TENKH (#PCDATA)>
<!ELEMENT DC (#PCDATA)>
<!ELEMENT ORDERS (%infoMH;)>
<!ELEMENT MMH (#PCDATA)>
<!ELEMENT TENMH (#PCDATA)>
<!ELEMENT SL (#PCDATA)>
<!ELEMENT DONGIA (#PCDATA)>

=== HM9901/XML/QLDH.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DOCUMENT SYSTEM "file:/D:/HK2-thirdYear/XML/repos/QLDH.dtd">
<DOCUMENT>
    <KHACHHANG>
        <MSKH></MSKH>
        <TENKH></TENKH>
        <DC></DC>
        <ORDERS>
            <MMH></MMH>
            <TENMH></TENMH>
            <SL></SL>
            <DONGIA></DONGIA>
        </ORDERS>
    </KHACHHANG>
</DOCUMENT>
