=== HM9901/XML/QLdia.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="SPECIALS">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="TITLE" type="xs:string"/>
                <xs:element name="MESSAGE" type="xs:string"/>
                <xs:element name="CD" >
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="ARTIST" type="xs:string"/>
                            <xs:element name="PRICEUS" type="xs:decimal"/>
                            <xs:element name="PRICEVN" type="xs:decimal"/>
                            <xs:element name="TRACK" maxOccurs="unbounded">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="NAME" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="LENGTH" type="xs:unsignedByte"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== HM9901/XML/QLDia1.xml
<?xml version="1.0" encoding="UTF-8"?>
<SPECIALS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/HK2-thirdYear/XML/repos/QLdia.xsd">
    <TITLE>TITLE0</TITLE>
    <MESSAGE>MESSAGE0</MESSAGE>
    <CD>
        Ước Mơ Của Bé
        <ARTIST>ARTIST0</ARTIST>
        <PRICEUS>0</PRICEUS>
        <PRICEVN>0</PRICEVN>
        <TRACK>
            <NAME>NAME0</NAME>
        </TRACK>
        <TRACK>
            <NAME>NAME1</NAME>
        </TRACK>
    </CD>
</SPECIALS>
