=== HM9901/XML/QLKS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="DSKS">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Khachsan" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaKS">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z][a-zA-Z][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tenKS" type="xs:string"/>
                            <xs:element name="Diachi" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Phong" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaKS">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z][a-zA-Z][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Maphong">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[P][a-zA-Z][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TenLoai" type="xs:string"/>
                            <xs:element name="Dongia" type="xs:decimal"/>
                            <xs:element name="MaLP">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[L][a-zA-Z][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="LoaiPhong" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaLP">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[L][a-zA-Z][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tenPhong" type="xs:string"/>
                            <xs:element name="lau" type="xs:byte"/>
                            <xs:element name="SDT" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="DichVu" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaDichVu">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[DV][a-zA-Z][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tenDV" type="xs:string"/>
                            <xs:element name="dongia" type="xs:decimal"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="KhachHang" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaKH">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[KH][a-zA-Z][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tenKH" type="xs:string"/>
                            <xs:element name="DC" type="xs:string"/>
                            <xs:element name="CMND" type="xs:string"/>
                            <xs:element name="SDT" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="HoaDon" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaHD">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[HD][a-zA-Z][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="ngayden" type="xs:date"/>
                            <xs:element name="ngaydi" type="xs:date"/>
                            <xs:element name="MaPhong">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[P][a-zA-Z][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MaKH">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[KH][a-zA-Z][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="thanhTien"/>
                            <xs:element name="MaDV">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[DV][a-zA-Z][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="KSkey">
            <xs:selector xpath="Khachsan"/>
            <xs:field xpath="MaKS"/>
        </xs:key>
        <xs:key name="LPkey">
            <xs:selector xpath="LoaiPhong"/>
            <xs:field xpath="MaLP"/>
        </xs:key>
        <xs:key name="Pkey">
            <xs:selector xpath="Phong"/>
            <xs:field xpath="Maphong"/>
        </xs:key>
        <xs:key name="DVkey">
            <xs:selector xpath="DichVu"/>
            <xs:field xpath="MaDichVu"/>
        </xs:key>
        <xs:key name="KHkey">
            <xs:selector xpath="KhachHang"/>
            <xs:field xpath="MaKH"/>
        </xs:key>
        <xs:key name="HDkey">
            <xs:selector xpath="HoaDon"/>
            <xs:field xpath="MaHD"/>
        </xs:key>
        <xs:keyref name="KSrefkey" refer="KSkey">
            <xs:selector xpath="Phong"/>
            <xs:field xpath="MaKS"/>
        </xs:keyref>
        <xs:keyref name="LPrefkey" refer="LPkey">
            <xs:selector xpath="Phong"/>
            <xs:field xpath="MaLP"/>
        </xs:keyref>
        <xs:keyref name="HDrefkey" refer="KHkey">
            <xs:selector xpath="HoaDon"/>
            <xs:field xpath="MaKH"/>
        </xs:keyref>
        <xs:keyref name="dvkeyref" refer="DVkey">
            <xs:selector xpath="HoaDon"/>
            <xs:field xpath="MaDV"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== HM9901/XML/QLKS1.xml
<?xml version="1.0" encoding="UTF-8"?>
<DSKS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/HK2-thirdYear/XML/repos/QLKS.xsd">
    <Khachsan>
        <MaKS>AA00</MaKS>
        <tenKS>tenKS0</tenKS>
        <Diachi>Diachi0</Diachi>
    </Khachsan>
    <Khachsan>
        <MaKS>AA00</MaKS>
        <tenKS>tenKS1</tenKS>
        <Diachi>Diachi1</Diachi>
    </Khachsan>
    <Phong>
        <MaKS>AA00</MaKS>
        <Maphong>PA00</Maphong>
        <TenLoai>TenLoai0</TenLoai>
        <Dongia>0</Dongia>
        <MaLP>LA00</MaLP>
    </Phong>
    <Phong>
        <MaKS>AA00</MaKS>
        <Maphong>PA00</Maphong>
        <TenLoai>TenLoai1</TenLoai>
        <Dongia>0</Dongia>
        <MaLP>LA00</MaLP>
    </Phong>
    <LoaiPhong>
        <MaLP>LA00</MaLP>
        <tenPhong>tenPhong0</tenPhong>
        <lau>0</lau>
        <SDT>SDT0</SDT>
    </LoaiPhong>
    <LoaiPhong>
        <MaLP>LA00</MaLP>
        <tenPhong>tenPhong1</tenPhong>
        <lau>0</lau>
        <SDT>SDT1</SDT>
    </LoaiPhong>
    <DichVu>
        <MaDichVu>DA00</MaDichVu>
        <tenDV>tenDV0</tenDV>
        <dongia>0</dongia>
    </DichVu>
    <DichVu>
        <MaDichVu>DA00</MaDichVu>
        <tenDV>tenDV1</tenDV>
        <dongia>0</dongia>
    </DichVu>
    <KhachHang>
        <MaKH>HA00</MaKH>
        <tenKH>tenKH0</tenKH>
        <DC>DC0</DC>
        <CMND>CMND0</CMND>
        <SDT>SDT2</SDT>
    </KhachHang>
    <KhachHang>
        <MaKH>HA00</MaKH>
        <tenKH>tenKH1</tenKH>
        <DC>DC1</DC>
        <CMND>CMND1</CMND>
        <SDT>SDT3</SDT>
    </KhachHang>
    <HoaDon>
        <MaHD>DA00</MaHD>
        <ngayden>2006-05-04</ngayden>
        <ngaydi>2006-05-04</ngaydi>
        <MaPhong>PA00</MaPhong>
        <MaKH>HA00</MaKH>
        <thanhTien>
        </thanhTien>
        <MaDV>DA00</MaDV>
    </HoaDon>
    <HoaDon>
        <MaHD>DA00</MaHD>
        <ngayden>2006-05-04</ngayden>
        <ngaydi>2006-05-04</ngaydi>
        <MaPhong>PA00</MaPhong>
        <MaKH>HA00</MaKH>
        <thanhTien>
        </thanhTien>
        <MaDV>DA00</MaDV>
    </HoaDon>
</DSKS>
